name: api_for_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  shelf: ^1.4.1
  #路由
  shelf_router: ^1.1.4
  #数据库
  postgres: ^2.6.2
  #数据库 mysql
  mysql1: ^0.20.0
  #缓存
  redis: ^3.1.0
  #身份验证和授权
  crypto: ^3.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
